### ISSUE TITLE
Ticket N°5::2: Perform a hotfix release

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/release-script#12]
This feature is copied from the previous project https://github.com/adorsys/release-scripts/?tab=readme-ov-file#perform-a-hotfix-release.

**Comment by AssahBismarkabah** [comment]
hello sir @stephane-segning please ticket  #12 and  #13 has some repetition

**Comment by Awambeng** [comment]
Repetition with ticket #13
